# Params for the parallel gripper node

# Port
port: '/dev/ttyUSB0'

# Motor ID
motor_id: 0

# Gripper state publish rate
publish_rate: 125  # [Hz]

# Path to calibration file
cal_file_path: "/home/felipe/skill_transfer/catkin_ws/src/skill_t_bringup/config/parallel_cal.csv"

# URDF joint names whose states are published
joint_names:
  - ur5e_A_finger_mount_joint1
  - ur5e_A_finger_mount_joint2

# Maximum gripper aperture [m]
max_aperture: 0.135

# Default motor velocity, if not specified in action goal
default_velocity: 30        # Motor speed

# Default effort, if not specified in action goal
default_effort: 100          # Motor current