// Generated by gencpp from file rgmc_manipulation/NFSRequestResponse.msg
// DO NOT EDIT!


#ifndef RGMC_MANIPULATION_MESSAGE_NFSREQUESTRESPONSE_H
#define RGMC_MANIPULATION_MESSAGE_NFSREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rgmc_manipulation
{
template <class ContainerAllocator>
struct NFSRequestResponse_
{
  typedef NFSRequestResponse_<ContainerAllocator> Type;

  NFSRequestResponse_()
    : result(false)  {
    }
  NFSRequestResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NFSRequestResponse_

typedef ::rgmc_manipulation::NFSRequestResponse_<std::allocator<void> > NFSRequestResponse;

typedef boost::shared_ptr< ::rgmc_manipulation::NFSRequestResponse > NFSRequestResponsePtr;
typedef boost::shared_ptr< ::rgmc_manipulation::NFSRequestResponse const> NFSRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rgmc_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rgmc_manipulation/NFSRequestResponse";
  }

  static const char* value(const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NFSRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rgmc_manipulation::NFSRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RGMC_MANIPULATION_MESSAGE_NFSREQUESTRESPONSE_H
