// Generated by gencpp from file rgmc_manipulation/NFSRequest.msg
// DO NOT EDIT!


#ifndef RGMC_MANIPULATION_MESSAGE_NFSREQUEST_H
#define RGMC_MANIPULATION_MESSAGE_NFSREQUEST_H

#include <ros/service_traits.h>


#include <rgmc_manipulation/NFSRequestRequest.h>
#include <rgmc_manipulation/NFSRequestResponse.h>


namespace rgmc_manipulation
{

struct NFSRequest
{

typedef NFSRequestRequest Request;
typedef NFSRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NFSRequest
} // namespace rgmc_manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rgmc_manipulation::NFSRequest > {
  static const char* value()
  {
    return "1297a10f19670677860ac0dedc54bb5d";
  }

  static const char* value(const ::rgmc_manipulation::NFSRequest&) { return value(); }
};

template<>
struct DataType< ::rgmc_manipulation::NFSRequest > {
  static const char* value()
  {
    return "rgmc_manipulation/NFSRequest";
  }

  static const char* value(const ::rgmc_manipulation::NFSRequest&) { return value(); }
};


// service_traits::MD5Sum< ::rgmc_manipulation::NFSRequestRequest> should match
// service_traits::MD5Sum< ::rgmc_manipulation::NFSRequest >
template<>
struct MD5Sum< ::rgmc_manipulation::NFSRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rgmc_manipulation::NFSRequest >::value();
  }
  static const char* value(const ::rgmc_manipulation::NFSRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgmc_manipulation::NFSRequestRequest> should match
// service_traits::DataType< ::rgmc_manipulation::NFSRequest >
template<>
struct DataType< ::rgmc_manipulation::NFSRequestRequest>
{
  static const char* value()
  {
    return DataType< ::rgmc_manipulation::NFSRequest >::value();
  }
  static const char* value(const ::rgmc_manipulation::NFSRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rgmc_manipulation::NFSRequestResponse> should match
// service_traits::MD5Sum< ::rgmc_manipulation::NFSRequest >
template<>
struct MD5Sum< ::rgmc_manipulation::NFSRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rgmc_manipulation::NFSRequest >::value();
  }
  static const char* value(const ::rgmc_manipulation::NFSRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgmc_manipulation::NFSRequestResponse> should match
// service_traits::DataType< ::rgmc_manipulation::NFSRequest >
template<>
struct DataType< ::rgmc_manipulation::NFSRequestResponse>
{
  static const char* value()
  {
    return DataType< ::rgmc_manipulation::NFSRequest >::value();
  }
  static const char* value(const ::rgmc_manipulation::NFSRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RGMC_MANIPULATION_MESSAGE_NFSREQUEST_H
