// Generated by gencpp from file rgmc_manipulation/ParallelSpinPadsGripperCommandAction.msg
// DO NOT EDIT!


#ifndef RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTION_H
#define RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rgmc_manipulation/ParallelSpinPadsGripperCommandActionGoal.h>
#include <rgmc_manipulation/ParallelSpinPadsGripperCommandActionResult.h>
#include <rgmc_manipulation/ParallelSpinPadsGripperCommandActionFeedback.h>

namespace rgmc_manipulation
{
template <class ContainerAllocator>
struct ParallelSpinPadsGripperCommandAction_
{
  typedef ParallelSpinPadsGripperCommandAction_<ContainerAllocator> Type;

  ParallelSpinPadsGripperCommandAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ParallelSpinPadsGripperCommandAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> const> ConstPtr;

}; // struct ParallelSpinPadsGripperCommandAction_

typedef ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<std::allocator<void> > ParallelSpinPadsGripperCommandAction;

typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction > ParallelSpinPadsGripperCommandActionPtr;
typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction const> ParallelSpinPadsGripperCommandActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rgmc_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f38eebbc7d7baeb4c02f8e30dc3e5371";
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf38eebbc7d7baeb4ULL;
  static const uint64_t static_value2 = 0xc02f8e30dc3e5371ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rgmc_manipulation/ParallelSpinPadsGripperCommandAction";
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ParallelSpinPadsGripperCommandActionGoal action_goal\n"
"ParallelSpinPadsGripperCommandActionResult action_result\n"
"ParallelSpinPadsGripperCommandActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ParallelSpinPadsGripperCommandGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# When performing an action that uses the parallel jaw and the pads at the same time,\n"
"# The parallel jaw one will be done first.\n"
"# GOAL\n"
"float64 par_target_pos  # Parallel gripper target aperture (in meters)\n"
"float64 par_max_effort  # Parallel gripper motor max motor current\n"
"float64 par_velocity    # Parallel gripper motor velocity\n"
"bool actuate_parallel   # Whether to actuate the parallel gripper or not\n"
"float64 pads_target_pos # Fingertip pads target angular position (in radians)\n"
"float64 pads_max_effort # Fingertip pads motor max current (in mA)\n"
"float64 pads_velocity   # Fingertip pads motor target velocity\n"
"bool actuate_pads       # Whether to actuate the rotary pads or not\n"
"bool reverse_pads_actuation       # Actuate rotary pads in reverse\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ParallelSpinPadsGripperCommandResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# RESULT\n"
"float64 par_final_position  # The final parallel gripper gap size (in meters)\n"
"float64 par_final_effort    # The final parallel gripper effort exerted (motor current)\n"
"bool par_stalled      # True iff the gripper is exerting max effort and not moving\n"
"bool par_reached_goal # True iff the gripper position has reached the commanded setpoint\n"
"float64[] pads_final_position # The final fingertip pads angular position (in radians)\n"
"float64[] pads_final_effort   # The final fingertip pads effort (in mA)\n"
"bool pads_stalled      # True iff one of the pads is exerting max effort and not moving\n"
"bool pads_reached_goal # True iff both pads reached goal position\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ParallelSpinPadsGripperCommandFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# FEEDBACK\n"
"float64 par_position  # The current parallel gripper gap size (in meters)\n"
"float64 par_effort    # The current parallel gripper effort exerted (motor current)\n"
"float64[] pads_position # The current fingertip pads angular position (in radians)\n"
"float64[] pads_effort   # The current fingertip pads effort (in mA)\n"
;
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParallelSpinPadsGripperCommandAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTION_H
