// Generated by gencpp from file rgmc_manipulation/ParallelSpinPadsGripperCommandActionGoal.msg
// DO NOT EDIT!


#ifndef RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTIONGOAL_H
#define RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <rgmc_manipulation/ParallelSpinPadsGripperCommandGoal.h>

namespace rgmc_manipulation
{
template <class ContainerAllocator>
struct ParallelSpinPadsGripperCommandActionGoal_
{
  typedef ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> Type;

  ParallelSpinPadsGripperCommandActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ParallelSpinPadsGripperCommandActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::rgmc_manipulation::ParallelSpinPadsGripperCommandGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ParallelSpinPadsGripperCommandActionGoal_

typedef ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<std::allocator<void> > ParallelSpinPadsGripperCommandActionGoal;

typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal > ParallelSpinPadsGripperCommandActionGoalPtr;
typedef boost::shared_ptr< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal const> ParallelSpinPadsGripperCommandActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator1> & lhs, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rgmc_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46d5d84b1efa4d94b67a02040b950378";
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46d5d84b1efa4d94ULL;
  static const uint64_t static_value2 = 0xb67a02040b950378ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rgmc_manipulation/ParallelSpinPadsGripperCommandActionGoal";
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ParallelSpinPadsGripperCommandGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# When performing an action that uses the parallel jaw and the pads at the same time,\n"
"# The parallel jaw one will be done first.\n"
"# GOAL\n"
"float64 par_target_pos  # Parallel gripper target aperture (in meters)\n"
"float64 par_max_effort  # Parallel gripper motor max motor current\n"
"float64 par_velocity    # Parallel gripper motor velocity\n"
"bool actuate_parallel   # Whether to actuate the parallel gripper or not\n"
"float64 pads_target_pos # Fingertip pads target angular position (in radians)\n"
"float64 pads_max_effort # Fingertip pads motor max current (in mA)\n"
"float64 pads_velocity   # Fingertip pads motor target velocity\n"
"bool actuate_pads       # Whether to actuate the rotary pads or not\n"
"bool reverse_pads_actuation       # Actuate rotary pads in reverse\n"
;
  }

  static const char* value(const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParallelSpinPadsGripperCommandActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rgmc_manipulation::ParallelSpinPadsGripperCommandActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::rgmc_manipulation::ParallelSpinPadsGripperCommandGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RGMC_MANIPULATION_MESSAGE_PARALLELSPINPADSGRIPPERCOMMANDACTIONGOAL_H
