set(_CATKIN_CURRENT_PACKAGE "ndx_manipulation")
set(ndx_manipulation_VERSION "0.0.0")
set(ndx_manipulation_MAINTAINER "Gal Gorjup <ggor290@aucklanduni.ac.nz>")
set(ndx_manipulation_PACKAGE_FORMAT "2")
set(ndx_manipulation_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "actionlib" "actionlib_msgs")
set(ndx_manipulation_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "actionlib" "actionlib_msgs")
set(ndx_manipulation_BUILDTOOL_DEPENDS "catkin")
set(ndx_manipulation_BUILDTOOL_EXPORT_DEPENDS )
set(ndx_manipulation_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "actionlib" "actionlib_msgs")
set(ndx_manipulation_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "actionlib" "actionlib_msgs")
set(ndx_manipulation_TEST_DEPENDS )
set(ndx_manipulation_DOC_DEPENDS )
set(ndx_manipulation_URL_WEBSITE "")
set(ndx_manipulation_URL_BUGTRACKER "")
set(ndx_manipulation_URL_REPOSITORY "")
set(ndx_manipulation_DEPRECATED "")