set(ndx_manipulation_SETUP_PY_SETUP_MODULE "distutils.core")
set(ndx_manipulation_SETUP_PY_VERSION "0.0.0")
set(ndx_manipulation_SETUP_PY_SCRIPTS "")
set(ndx_manipulation_SETUP_PY_PACKAGES "ndx_manipulation")
set(ndx_manipulation_SETUP_PY_PACKAGE_DIRS "src/ndx_manipulation")
set(ndx_manipulation_SETUP_PY_MODULES "")
set(ndx_manipulation_SETUP_PY_MODULE_DIRS "")