(cl:defpackage rgmc_manipulation-msg
  (:use )
  (:export
   "<PARALLELSPINPADSGRIPPERCOMMANDACTION>"
   "PARALLELSPINPADSGRIPPERCOMMANDACTION"
   "<PARALLELSPINPADSGRIPPERCOMMANDACTIONFEEDBACK>"
   "PARALLELSPINPADSGRIPPERCOMMANDACTIONFEEDBACK"
   "<PARALLELSPINPADSGRIPPERCOMMANDACTIONGOAL>"
   "PARALLELSPINPADSGRIPPERCOMMANDACTIONGOAL"
   "<PARALLELSPINPADSGRIPPERCOMMANDACTIONRESULT>"
   "PARALLELSPINPADSGRIPPERCOMMANDACTIONRESULT"
   "<PARALLELSPINPADSGRIPPERCOMMANDFEEDBACK>"
   "PARALLELSPINPADSGRIPPERCOMMANDFEEDBACK"
   "<PARALLELSPINPADSGRIPPERCOMMANDGOAL>"
   "PARALLELSPINPADSGRIPPERCOMMANDGOAL"
   "<PARALLELSPINPADSGRIPPERCOMMANDRESULT>"
   "PARALLELSPINPADSGRIPPERCOMMANDRESULT"
  ))

