#! /usr/bin/env python

import time
import rospy
import actionlib
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray
from ndx_manipulation.msg import GripperCommandAction, GripperCommandFeedback, GripperCommandResult
from threading import Lock


class ParallelGripper(object):
    # create messages that are used to publish feedback/result
    _feedback = GripperCommandFeedback()
    _result = GripperCommandResult()

    def __init__(self, name):

        # Mutex for motor IO
        self.mutex = Lock()

        # Parameters
        self.rate_hz = rospy.get_param("~publish_rate")
        self.default_velocity = rospy.get_param("~default_velocity")
        self.default_effort = rospy.get_param("~default_effort")
        self.joint_names = rospy.get_param("~joint_names")
        self.max_aperture = rospy.get_param("~max_aperture")

        # Gripper variables
        self.aperture = 0

        # Initialise joint state subscriber
        self._js_sub = rospy.Subscriber('joint_states', JointState, self.joint_state_callback, queue_size=1)

        # Initialise gripper command publisher
        self._gripper_pub = rospy.Publisher('hand_controller/command', Float64MultiArray, queue_size=1)

        # Start action server
        self._action_name = name
        self._as = actionlib.SimpleActionServer(self._action_name, GripperCommandAction,
                                                execute_cb=self.execute_callback, auto_start=False)
        self._as.start()

    def joint_state_callback(self, data):
        self.aperture = data.position[data.name.index(self.joint_names[0])] + data.position[data.name.index(self.joint_names[1])]

    def publish_gripper_command(self, aperture):
        msg = Float64MultiArray()
        msg.data = [aperture/2, aperture/2]
        self._gripper_pub.publish(msg)

    def execute_callback(self, goal):
        # Variables
        max_time = 5.0
        rate = rospy.Rate(self.rate_hz)
        success = True
        reached_goal = False
        stalled = True

        # Bound requested aperture
        desired_aperture = goal.position
        if desired_aperture > self.max_aperture:
            desired_aperture = self.max_aperture
        if desired_aperture < 0:
            desired_aperture = 0

        # Print inputs
        rospy.loginfo("{}: Executing, setting gripper to aperture {}"
                      .format(self._action_name, desired_aperture))

        # Set goal aperture
        self.publish_gripper_command(desired_aperture)

        # Loop until at goal or preempted
        for i in range(int(max_time * self.rate_hz)):
            rate.sleep()

            # If at goal, break loop
            if abs(self.aperture - desired_aperture) < 0.003:
                stalled = False
                reached_goal = True
                break

            # Check that preempt has not been requested by the client
            if self._as.is_preempt_requested():
                rospy.loginfo("{}: Preempted".format(self._action_name))
                self._as.set_preempted()
                success = False
                break

            # Publish feedback
            self._feedback.position = self.aperture
            self._feedback.effort = 0
            self._feedback.reached_goal = reached_goal
            self._feedback.stalled = stalled
            self._as.publish_feedback(self._feedback)

        if success:
            # Set goal positions as they are
            self.publish_gripper_command(self.aperture)

            # Return result
            self._result.position = self.aperture
            self._result.effort = 0
            self._result.reached_goal = reached_goal
            self._result.stalled = stalled
            rospy.loginfo("{}: Succeeded".format(self._action_name))
            self._as.set_succeeded(self._result)

    def run(self):
        rospy.spin()


if __name__ == '__main__':
    # Initialise node
    rospy.init_node('gripper')

    # Start server
    c = ParallelGripper(rospy.get_name())
    c.run()
