set(_CATKIN_CURRENT_PACKAGE "camera_sim_config")
set(camera_sim_config_VERSION "0.3.0")
set(camera_sim_config_MAINTAINER "Andrew Koh <andyjkoh@gmail.com>")
set(camera_sim_config_PACKAGE_FORMAT "1")
set(camera_sim_config_BUILD_DEPENDS )
set(camera_sim_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "pose_estimation")
set(camera_sim_config_BUILDTOOL_DEPENDS "catkin")
set(camera_sim_config_BUILDTOOL_EXPORT_DEPENDS )
set(camera_sim_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "pose_estimation")
set(camera_sim_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "pose_estimation")
set(camera_sim_config_TEST_DEPENDS )
set(camera_sim_config_DOC_DEPENDS )
set(camera_sim_config_URL_WEBSITE "http://moveit.ros.org/")
set(camera_sim_config_URL_BUGTRACKER "https://github.com/moveit/moveit/issues")
set(camera_sim_config_URL_REPOSITORY "https://github.com/moveit/moveit")
set(camera_sim_config_DEPRECATED "")