; Auto-generated. Do not edit!


(cl:in-package ndx_manipulation-msg)


;//! \htmlinclude TFGCommandActionGoal.msg.html

(cl:defclass <TFGCommandActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type ndx_manipulation-msg:TFGCommandGoal
    :initform (cl:make-instance 'ndx_manipulation-msg:TFGCommandGoal)))
)

(cl:defclass TFGCommandActionGoal (<TFGCommandActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TFGCommandActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TFGCommandActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ndx_manipulation-msg:<TFGCommandActionGoal> is deprecated: use ndx_manipulation-msg:TFGCommandActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <TFGCommandActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ndx_manipulation-msg:header-val is deprecated.  Use ndx_manipulation-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <TFGCommandActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ndx_manipulation-msg:goal_id-val is deprecated.  Use ndx_manipulation-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <TFGCommandActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ndx_manipulation-msg:goal-val is deprecated.  Use ndx_manipulation-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TFGCommandActionGoal>) ostream)
  "Serializes a message object of type '<TFGCommandActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TFGCommandActionGoal>) istream)
  "Deserializes a message object of type '<TFGCommandActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TFGCommandActionGoal>)))
  "Returns string type for a message object of type '<TFGCommandActionGoal>"
  "ndx_manipulation/TFGCommandActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TFGCommandActionGoal)))
  "Returns string type for a message object of type 'TFGCommandActionGoal"
  "ndx_manipulation/TFGCommandActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TFGCommandActionGoal>)))
  "Returns md5sum for a message object of type '<TFGCommandActionGoal>"
  "94a2a2bdb70b0db404a375c90a249d54")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TFGCommandActionGoal)))
  "Returns md5sum for a message object of type 'TFGCommandActionGoal"
  "94a2a2bdb70b0db404a375c90a249d54")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TFGCommandActionGoal>)))
  "Returns full string definition for message of type '<TFGCommandActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%TFGCommandGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ndx_manipulation/TFGCommandGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 grasp           # Gripper open or close~%float64 finger_angle    # Angle between finger 2 and finger 3~%bool is_deg             # Specify if Angle is in degrees~%float64 max_effort      # Max motor current~%float64 velocity        # Motor velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TFGCommandActionGoal)))
  "Returns full string definition for message of type 'TFGCommandActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%TFGCommandGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: ndx_manipulation/TFGCommandGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 grasp           # Gripper open or close~%float64 finger_angle    # Angle between finger 2 and finger 3~%bool is_deg             # Specify if Angle is in degrees~%float64 max_effort      # Max motor current~%float64 velocity        # Motor velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TFGCommandActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TFGCommandActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TFGCommandActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
