set(_CATKIN_CURRENT_PACKAGE "pcl_pose_estimation")
set(pcl_pose_estimation_VERSION "0.0.0")
set(pcl_pose_estimation_MAINTAINER "akoh751 <akoh751@todo.todo>")
set(pcl_pose_estimation_PACKAGE_FORMAT "2")
set(pcl_pose_estimation_BUILD_DEPENDS "eigen_conversions" "flann" "pcl_conversions" "pcl_ros" "roscpp" "hdf5" "std_msgs")
set(pcl_pose_estimation_BUILD_EXPORT_DEPENDS "eigen_conversions" "flann" "pcl_conversions" "pcl_ros" "roscpp" "hdf5" "std_msgs")
set(pcl_pose_estimation_BUILDTOOL_DEPENDS "catkin")
set(pcl_pose_estimation_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_pose_estimation_EXEC_DEPENDS "eigen_conversions" "flann" "pcl_conversions" "pcl_ros" "roscpp" "hdf5" "std_msgs")
set(pcl_pose_estimation_RUN_DEPENDS "eigen_conversions" "flann" "pcl_conversions" "pcl_ros" "roscpp" "hdf5" "std_msgs")
set(pcl_pose_estimation_TEST_DEPENDS )
set(pcl_pose_estimation_DOC_DEPENDS )
set(pcl_pose_estimation_URL_WEBSITE "")
set(pcl_pose_estimation_URL_BUGTRACKER "")
set(pcl_pose_estimation_URL_REPOSITORY "")
set(pcl_pose_estimation_DEPRECATED "")