// Auto-generated. Do not edit!

// (in-package rgmc_manipulation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ParallelSpinPadsGripperCommandActionGoal = require('./ParallelSpinPadsGripperCommandActionGoal.js');
let ParallelSpinPadsGripperCommandActionResult = require('./ParallelSpinPadsGripperCommandActionResult.js');
let ParallelSpinPadsGripperCommandActionFeedback = require('./ParallelSpinPadsGripperCommandActionFeedback.js');

//-----------------------------------------------------------

class ParallelSpinPadsGripperCommandAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new ParallelSpinPadsGripperCommandActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new ParallelSpinPadsGripperCommandActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new ParallelSpinPadsGripperCommandActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ParallelSpinPadsGripperCommandAction
    // Serialize message field [action_goal]
    bufferOffset = ParallelSpinPadsGripperCommandActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = ParallelSpinPadsGripperCommandActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = ParallelSpinPadsGripperCommandActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ParallelSpinPadsGripperCommandAction
    let len;
    let data = new ParallelSpinPadsGripperCommandAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = ParallelSpinPadsGripperCommandActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = ParallelSpinPadsGripperCommandActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = ParallelSpinPadsGripperCommandActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += ParallelSpinPadsGripperCommandActionGoal.getMessageSize(object.action_goal);
    length += ParallelSpinPadsGripperCommandActionResult.getMessageSize(object.action_result);
    length += ParallelSpinPadsGripperCommandActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rgmc_manipulation/ParallelSpinPadsGripperCommandAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f38eebbc7d7baeb4c02f8e30dc3e5371';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ParallelSpinPadsGripperCommandActionGoal action_goal
    ParallelSpinPadsGripperCommandActionResult action_result
    ParallelSpinPadsGripperCommandActionFeedback action_feedback
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    ParallelSpinPadsGripperCommandGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # When performing an action that uses the parallel jaw and the pads at the same time,
    # The parallel jaw one will be done first.
    # GOAL
    float64 par_target_pos  # Parallel gripper target aperture (in meters)
    float64 par_max_effort  # Parallel gripper motor max motor current
    float64 par_velocity    # Parallel gripper motor velocity
    bool actuate_parallel   # Whether to actuate the parallel gripper or not
    float64 pads_target_pos # Fingertip pads target angular position (in radians)
    float64 pads_max_effort # Fingertip pads motor max current (in mA)
    float64 pads_velocity   # Fingertip pads motor target velocity
    bool actuate_pads       # Whether to actuate the rotary pads or not
    bool reverse_pads_actuation       # Actuate rotary pads in reverse
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ParallelSpinPadsGripperCommandResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # RESULT
    float64 par_final_position  # The final parallel gripper gap size (in meters)
    float64 par_final_effort    # The final parallel gripper effort exerted (motor current)
    bool par_stalled      # True iff the gripper is exerting max effort and not moving
    bool par_reached_goal # True iff the gripper position has reached the commanded setpoint
    float64[] pads_final_position # The final fingertip pads angular position (in radians)
    float64[] pads_final_effort   # The final fingertip pads effort (in mA)
    bool pads_stalled      # True iff one of the pads is exerting max effort and not moving
    bool pads_reached_goal # True iff both pads reached goal position
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ParallelSpinPadsGripperCommandFeedback feedback
    
    ================================================================================
    MSG: rgmc_manipulation/ParallelSpinPadsGripperCommandFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # FEEDBACK
    float64 par_position  # The current parallel gripper gap size (in meters)
    float64 par_effort    # The current parallel gripper effort exerted (motor current)
    float64[] pads_position # The current fingertip pads angular position (in radians)
    float64[] pads_effort   # The current fingertip pads effort (in mA)
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ParallelSpinPadsGripperCommandAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = ParallelSpinPadsGripperCommandActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new ParallelSpinPadsGripperCommandActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = ParallelSpinPadsGripperCommandActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new ParallelSpinPadsGripperCommandActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = ParallelSpinPadsGripperCommandActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new ParallelSpinPadsGripperCommandActionFeedback()
    }

    return resolved;
    }
};

module.exports = ParallelSpinPadsGripperCommandAction;
