set(_CATKIN_CURRENT_PACKAGE "collision_objects")
set(collision_objects_VERSION "0.0.0")
set(collision_objects_MAINTAINER "akoh751 <akoh751@todo.todo>")
set(collision_objects_PACKAGE_FORMAT "2")
set(collision_objects_BUILD_DEPENDS "geometry_msgs" "moveit_commander" "rospy" "visualization_msgs")
set(collision_objects_BUILD_EXPORT_DEPENDS "geometry_msgs" "moveit_commander" "rospy" "visualization_msgs")
set(collision_objects_BUILDTOOL_DEPENDS "catkin")
set(collision_objects_BUILDTOOL_EXPORT_DEPENDS )
set(collision_objects_EXEC_DEPENDS "geometry_msgs" "moveit_commander" "rospy" "visualization_msgs")
set(collision_objects_RUN_DEPENDS "geometry_msgs" "moveit_commander" "rospy" "visualization_msgs")
set(collision_objects_TEST_DEPENDS )
set(collision_objects_DOC_DEPENDS )
set(collision_objects_URL_WEBSITE "")
set(collision_objects_URL_BUGTRACKER "")
set(collision_objects_URL_REPOSITORY "")
set(collision_objects_DEPRECATED "")