# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 500

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - ur5e_B/shoulder_pan_joint
     - ur5e_B/shoulder_lift_joint
     - ur5e_B/elbow_joint
     - ur5e_B/wrist_1_joint
     - ur5e_B/wrist_2_joint
     - ur5e_B/wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: *loop_hz

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: *loop_hz

# Publish speed_scaling factor
speed_scaling_state_controller:
   type:         scaled_controllers/SpeedScalingStateController
   publish_rate: *loop_hz

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scaled_pos_joint_traj_controller:
   type: position_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5e_B/shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/elbow_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

pos_joint_traj_controller:
   type: position_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5e_B/shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/elbow_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      ur5e_B/wrist_3_joint: {trajectory: 0.2, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

scaled_vel_joint_traj_controller:
   type: velocity_controllers/ScaledJointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5e_B/shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      ur5e_B/shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      ur5e_B/shoulder_pan_joint: 1.0
      ur5e_B/shoulder_lift_joint: 1.0
      ur5e_B/elbow_joint: 1.0
      ur5e_B/wrist_1_joint: 1.0
      ur5e_B/wrist_2_joint: 1.0
      ur5e_B/wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

vel_joint_traj_controller:
   type: velocity_controllers/JointTrajectoryController
   joints: *robot_joints
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5e_B/shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur5e_B/wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   gains:
      #!!These values have not been optimized!!
      ur5e_B/shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
      ur5e_B/wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
   # Use a feedforward term to reduce the size of PID gains
   velocity_ff:
      ur5e_B/shoulder_pan_joint: 1.0
      ur5e_B/shoulder_lift_joint: 1.0
      ur5e_B/elbow_joint: 1.0
      ur5e_B/wrist_1_joint: 1.0
      ur5e_B/wrist_2_joint: 1.0
      ur5e_B/wrist_3_joint: 1.0
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints: *robot_joints

forward_joint_traj_controller:
    type: "pass_through_controllers/JointTrajectoryController"
    joints: *robot_joints

forward_cartesian_traj_controller:
    type: "pass_through_controllers/CartesianTrajectoryController"
    joints: *robot_joints

twist_controller:
  type: "ros_controllers_cartesian/TwistController"
  frame_id: "tool0_controller"
  publish_rate: *loop_hz
  joints: *robot_joints

pose_based_cartesian_traj_controller:
    type: pose_controllers/CartesianTrajectoryController

    # UR driver convention
    base: ur5e_B/base
    tip: ur5e_B/tool0_controller
    joints: *robot_joints

joint_based_cartesian_traj_controller:
    type: position_controllers/CartesianTrajectoryController

    # UR driver convention
    base: ur5e_B/base
    tip: ur5e_B/tool0
    joints: *robot_joints

robot_status_controller:
   type: industrial_robot_status_controller/IndustrialRobotStatusController
   handle_name: industrial_robot_status_handle
   publish_rate: 10

cartesian_compliance_controller:
    type: "position_controllers/CartesianComplianceController"
   #  end_effector_link: "ur5e_B/tool0"
    end_effector_link: "ur5e_B_fingertip"
    robot_base_link: "ur5e_B/base_link"
    ft_sensor_ref_link: "ur5e_B_fingertip"
    compliance_ref_link: "ur5e_B_fingertip"
    target_frame_topic: "/ur5e_B/compliance_target_frame"
    joints:
    - ur5e_B/shoulder_pan_joint
    - ur5e_B/shoulder_lift_joint
    - ur5e_B/elbow_joint
    - ur5e_B/wrist_1_joint
    - ur5e_B/wrist_2_joint
    - ur5e_B/wrist_3_joint

    stiffness:
        trans_x: 500
        trans_y: 500
        trans_z: 500
        rot_x: 100
        rot_y: 100
        rot_z: 100

    solver:
        error_scale: 0.25
      #   iterations: 1
      #   forward_dynamics:
      #       link_mass: 0.3  # Higher values decrease oscillations in fully stretched configurations

    pd_gains:
        trans_x: {p: 0.02, d: 0.0005}
        trans_y: {p: 0.02, d: 0.0005}
        trans_z: {p: 0.02, d: 0.0005}
        rot_x: {p: 0.50}
        rot_y: {p: 0.50}
        rot_z: {p: 0.50}

motion_control_handle:
   type: "cartesian_controllers/MotionControlHandle"
   end_effector_link: "ur5e_B/tool0"
   robot_base_link: "ur5e_B/base_link"
   target_frame_topic: "/ur5e_B/compliance_target_frame"
   joints:
    - ur5e_B/shoulder_pan_joint
    - ur5e_B/shoulder_lift_joint
    - ur5e_B/elbow_joint
    - ur5e_B/wrist_1_joint
    - ur5e_B/wrist_2_joint
    - ur5e_B/wrist_3_joint