set(_CATKIN_CURRENT_PACKAGE "pcl_object_recognition")
set(pcl_object_recognition_VERSION "0.0.1")
set(pcl_object_recognition_MAINTAINER "vcol141 <vcol41@example.com>")
set(pcl_object_recognition_PACKAGE_FORMAT "2")
set(pcl_object_recognition_BUILD_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "Boost" "FLANN" "HDF5" "realsense2")
set(pcl_object_recognition_BUILD_EXPORT_DEPENDS )
set(pcl_object_recognition_BUILDTOOL_DEPENDS "catkin")
set(pcl_object_recognition_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_object_recognition_EXEC_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "Boost" "FLANN" "HDF5" "realsense2")
set(pcl_object_recognition_RUN_DEPENDS "roscpp" "pcl_ros" "pcl_conversions" "std_msgs" "Boost" "FLANN" "HDF5" "realsense2")
set(pcl_object_recognition_TEST_DEPENDS )
set(pcl_object_recognition_DOC_DEPENDS )
set(pcl_object_recognition_URL_WEBSITE "")
set(pcl_object_recognition_URL_BUGTRACKER "")
set(pcl_object_recognition_URL_REPOSITORY "")
set(pcl_object_recognition_DEPRECATED "")