// Generated by gencpp from file ndx_manipulation/RotaryGripperCommandActionGoal.msg
// DO NOT EDIT!


#ifndef NDX_MANIPULATION_MESSAGE_ROTARYGRIPPERCOMMANDACTIONGOAL_H
#define NDX_MANIPULATION_MESSAGE_ROTARYGRIPPERCOMMANDACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <ndx_manipulation/RotaryGripperCommandGoal.h>

namespace ndx_manipulation
{
template <class ContainerAllocator>
struct RotaryGripperCommandActionGoal_
{
  typedef RotaryGripperCommandActionGoal_<ContainerAllocator> Type;

  RotaryGripperCommandActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  RotaryGripperCommandActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::ndx_manipulation::RotaryGripperCommandGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RotaryGripperCommandActionGoal_

typedef ::ndx_manipulation::RotaryGripperCommandActionGoal_<std::allocator<void> > RotaryGripperCommandActionGoal;

typedef boost::shared_ptr< ::ndx_manipulation::RotaryGripperCommandActionGoal > RotaryGripperCommandActionGoalPtr;
typedef boost::shared_ptr< ::ndx_manipulation::RotaryGripperCommandActionGoal const> RotaryGripperCommandActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator1> & lhs, const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator1> & lhs, const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ndx_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89198261569fbedb58f4033aa6227248";
  }

  static const char* value(const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89198261569fbedbULL;
  static const uint64_t static_value2 = 0x58f4033aa6227248ULL;
};

template<class ContainerAllocator>
struct DataType< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ndx_manipulation/RotaryGripperCommandActionGoal";
  }

  static const char* value(const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"RotaryGripperCommandGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: ndx_manipulation/RotaryGripperCommandGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string type       # Can be 'open', 'close' or ''. If 'open' or 'close', clutch is engaged.\n"
"int32 offset      # Rotation offset. If positive, rotation is clockwise.\n"
"int32 effort      # Max motor current\n"
;
  }

  static const char* value(const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotaryGripperCommandActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ndx_manipulation::RotaryGripperCommandActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::ndx_manipulation::RotaryGripperCommandGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NDX_MANIPULATION_MESSAGE_ROTARYGRIPPERCOMMANDACTIONGOAL_H
