// Generated by gencpp from file ndx_manipulation/TFGCommandFeedback.msg
// DO NOT EDIT!


#ifndef NDX_MANIPULATION_MESSAGE_TFGCOMMANDFEEDBACK_H
#define NDX_MANIPULATION_MESSAGE_TFGCOMMANDFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ndx_manipulation
{
template <class ContainerAllocator>
struct TFGCommandFeedback_
{
  typedef TFGCommandFeedback_<ContainerAllocator> Type;

  TFGCommandFeedback_()
    : stalled(false)
    , reached_goal(false)  {
    }
  TFGCommandFeedback_(const ContainerAllocator& _alloc)
    : stalled(false)
    , reached_goal(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stalled_type;
  _stalled_type stalled;

   typedef uint8_t _reached_goal_type;
  _reached_goal_type reached_goal;





  typedef boost::shared_ptr< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TFGCommandFeedback_

typedef ::ndx_manipulation::TFGCommandFeedback_<std::allocator<void> > TFGCommandFeedback;

typedef boost::shared_ptr< ::ndx_manipulation::TFGCommandFeedback > TFGCommandFeedbackPtr;
typedef boost::shared_ptr< ::ndx_manipulation::TFGCommandFeedback const> TFGCommandFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator1> & lhs, const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.stalled == rhs.stalled &&
    lhs.reached_goal == rhs.reached_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator1> & lhs, const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ndx_manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71b044b88cc8e801ac03a8af68f2e9b1";
  }

  static const char* value(const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71b044b88cc8e801ULL;
  static const uint64_t static_value2 = 0xac03a8af68f2e9b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ndx_manipulation/TFGCommandFeedback";
  }

  static const char* value(const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool stalled            # True iff the gripper is exerting max effort and not moving\n"
"bool reached_goal       # True iff the gripper position has reached the commanded setpoint\n"
"\n"
;
  }

  static const char* value(const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stalled);
      stream.next(m.reached_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TFGCommandFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ndx_manipulation::TFGCommandFeedback_<ContainerAllocator>& v)
  {
    s << indent << "stalled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stalled);
    s << indent << "reached_goal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reached_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NDX_MANIPULATION_MESSAGE_TFGCOMMANDFEEDBACK_H
