# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ndx_manipulation/TFGCommandGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TFGCommandGoal(genpy.Message):
  _md5sum = "007cdeef6577eba1ad468b75850b155c"
  _type = "ndx_manipulation/TFGCommandGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64 grasp           # Gripper open or close
float64 finger_angle    # Angle between finger 2 and finger 3
bool is_deg             # Specify if Angle is in degrees
float64 max_effort      # Max motor current
float64 velocity        # Motor velocity
"""
  __slots__ = ['grasp','finger_angle','is_deg','max_effort','velocity']
  _slot_types = ['float64','float64','bool','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       grasp,finger_angle,is_deg,max_effort,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TFGCommandGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.grasp is None:
        self.grasp = 0.
      if self.finger_angle is None:
        self.finger_angle = 0.
      if self.is_deg is None:
        self.is_deg = False
      if self.max_effort is None:
        self.max_effort = 0.
      if self.velocity is None:
        self.velocity = 0.
    else:
      self.grasp = 0.
      self.finger_angle = 0.
      self.is_deg = False
      self.max_effort = 0.
      self.velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2dB2d().pack(_x.grasp, _x.finger_angle, _x.is_deg, _x.max_effort, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.grasp, _x.finger_angle, _x.is_deg, _x.max_effort, _x.velocity,) = _get_struct_2dB2d().unpack(str[start:end])
      self.is_deg = bool(self.is_deg)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2dB2d().pack(_x.grasp, _x.finger_angle, _x.is_deg, _x.max_effort, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.grasp, _x.finger_angle, _x.is_deg, _x.max_effort, _x.velocity,) = _get_struct_2dB2d().unpack(str[start:end])
      self.is_deg = bool(self.is_deg)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dB2d = None
def _get_struct_2dB2d():
    global _struct_2dB2d
    if _struct_2dB2d is None:
        _struct_2dB2d = struct.Struct("<2dB2d")
    return _struct_2dB2d
