; Auto-generated. Do not edit!


(cl:in-package ndx_manipulation-msg)


;//! \htmlinclude RotaryGripperCommandFeedback.msg.html

(cl:defclass <RotaryGripperCommandFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RotaryGripperCommandFeedback (<RotaryGripperCommandFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotaryGripperCommandFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotaryGripperCommandFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ndx_manipulation-msg:<RotaryGripperCommandFeedback> is deprecated: use ndx_manipulation-msg:RotaryGripperCommandFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotaryGripperCommandFeedback>) ostream)
  "Serializes a message object of type '<RotaryGripperCommandFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotaryGripperCommandFeedback>) istream)
  "Deserializes a message object of type '<RotaryGripperCommandFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotaryGripperCommandFeedback>)))
  "Returns string type for a message object of type '<RotaryGripperCommandFeedback>"
  "ndx_manipulation/RotaryGripperCommandFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotaryGripperCommandFeedback)))
  "Returns string type for a message object of type 'RotaryGripperCommandFeedback"
  "ndx_manipulation/RotaryGripperCommandFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotaryGripperCommandFeedback>)))
  "Returns md5sum for a message object of type '<RotaryGripperCommandFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotaryGripperCommandFeedback)))
  "Returns md5sum for a message object of type 'RotaryGripperCommandFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotaryGripperCommandFeedback>)))
  "Returns full string definition for message of type '<RotaryGripperCommandFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotaryGripperCommandFeedback)))
  "Returns full string definition for message of type 'RotaryGripperCommandFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotaryGripperCommandFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotaryGripperCommandFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RotaryGripperCommandFeedback
))
